<a href="https://colab.research.google.com/github/VKline333/Clarusway-DS-Students-08-21-/blob/main/week_1_students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Numpy Library**

In [1]:
import numpy as np

**https://www.w3resource.com/python-exercises/numpy/index-array.php**
- Numpy Questions: 4, 8, 9, 10, 12, 14, 19

**4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.**
<br>[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<br>Update sixth value to 11
<br>[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
arr=np.zeros(10)
arr[5]=11
print("Update sixth value to 11")
print(arr)

Update sixth value to 11
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [ ]:
print("Update sixth value to 11")
# ...

Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


**8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.**
![image-4.png](attachment:image-4.png)

In [20]:
arr=np.ones((5,5))
print("Original array:")
print(arr)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
print("Original array:")

# ...

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
arr[1:4,1:4]=0
print("1 on the border and 0 inside in the array")
print(arr)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
print("1 on the border and 0 inside in the array")

# ...

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**9. Write a NumPy program to add a border (filled with 0's) around an existing array.**
![image-2.png](attachment:image-2.png)

In [ ]:
print("Original array:")

# ...

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
arr=np.ones((3,3))
print("Original array:")
print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
arr=np.pad(arr, pad_width=1, mode="constant", constant_values=0)
print("0 on the border and 1 inside in the array")
print(arr)


0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print("0 on the border and 1 inside in the array")

# ...

0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.**
![image.png](attachment:image.png)

In [52]:
v=np.ones((3,3))
v

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# ...

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
v=np.zeros((8,8), dtype=int)
v

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [82]:
v[1::2]=1
v[:,[1,3,5,7]]=0
print("Checkerboard pattern:")
print(v)

Checkerboard pattern:
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [ ]:
print("Checkerboard pattern:")


# ...

Checkerboard pattern:


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# ...

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**12. Write a NumPy program to append values to the end of an array.**
![image-2.png](attachment:image-2.png)

In [ ]:
print("Original array:")

# ...


Original array:
[10, 20, 30]


In [94]:
a=np.arange(10,31,10)
print("Original array:")
print(a)

Original array:
[10 20 30]


In [ ]:
print("After append values to the end of the array:")

# ...


After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [97]:
b=np.arange(40,91,10)
print(b)
np.concatenate([a,b])

[40 50 60 70 80 90]


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
print("After append values to the end of the array:")
print(np.concatenate([a,b]))

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


  Another Solution

In [98]:
arr = np.append(a, [[40, 50, 60], [70, 80, 90]])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

**14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.**
![image.png](attachment:image.png)

In [ ]:
print("Values in Fahrenheit degrees:")

# ...


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]


In [102]:
F=[0,12,45.21,34,99.91]         # a list for fahrenheit degrees
F=np.array(F)
print("Values in Fahrenheit degrees:")
print(F)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]


In [ ]:
print("Values in  Centigrade degrees:") 

# ...


Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [105]:
# Centigrade degrees=(5*(Fahrenheit degrees-32))/9
C=(5*(F-32)/9)
print("Values in  Centigrade degrees:")
print(C)

Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


**19. Write a NumPy program to get the unique elements of an array.**
![image.png](attachment:image.png)

In [ ]:
print("Original array:")
# ...

Original array:
[10 10 20 20 30 30]


In [107]:
arr=np.array([10,10,20,20,30,30])
print("Original array:")
print(arr)

Original array:
[10 10 20 20 30 30]


In [ ]:
print("Unique elements of the above array:")

# ...


Unique elements of the above array:
[10 20 30]


In [109]:
print("Unique elements of the above array:")
print(np.unique(arr))

Unique elements of the above array:
[10 20 30]


In [ ]:
print("Original array:")

# ...


Original array:
[[1 1]
 [2 3]]


In [113]:
arr=np.array(([1,1],[2,3]))
print("Original array:")
print(arr)

Original array:
[[1 1]
 [2 3]]


In [ ]:
print("Unique elements of the above array:")

# ...


Unique elements of the above array:
[1 2 3]


In [114]:
print("Unique elements of the above array:")
print(np.unique(arr))

Unique elements of the above array:
[1 2 3]


# **import Pandas Library**

In [134]:
import pandas as pd

**https://www.w3resource.com/python-exercises/pandas/index-data-series.php**
- Pandas Questions: 2, 3, 5, 6, 13

**2. Write a Pandas program to convert a Pandas module Series to Python list and it's type.**

In [135]:
list_1 = [2, 4, 6, 8, 10]

In [141]:
# Convert the Python list to a Pandas Series 
print("Pandas Series and type")

ser=pd.Series(list_1)
print(ser)
type(ser)


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64


pandas.core.series.Series

In [142]:
# Convert the Pandas Series to Python list

list_1=ser.to_list()
list_1


[2, 4, 6, 8, 10]

**3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.**

In [119]:
list1 = [2, 4, 6, 8, 10]
list2 = [1, 3, 5, 7, 9]

In [143]:
# Create two Pandas series with these lists

ds1=pd.Series(list1)
ds2=pd.Series(list2)
ds1

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [144]:
ds2

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [145]:
print("Add two Series:")

ds1+ds2


Add two Series:


0     3
1     7
2    11
3    15
4    19
dtype: int64

In [146]:
print("Subtract two Series:")

ds1-ds2


Subtract two Series:


0    1
1    1
2    1
3    1
4    1
dtype: int64

In [147]:
print("Multiply two Series:")

ds1*ds2


Multiply two Series:


0     2
1    12
2    30
3    56
4    90
dtype: int64

In [148]:
print("Divide Series1 by Series2:")

ds1/ds2


Divide Series1 by Series2:


0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

**5. Write a Pandas program to convert a dictionary to a Pandas series.**

In [125]:
keys=['a','b','c','d','e']
values = [100, 200, 300, 400, 800]

In [149]:
# Create a dictionary from keys and values
print("Original dictionary:")

ser=pd.Series(values,keys)
ser


Original dictionary:


a    100
b    200
c    300
d    400
e    800
dtype: int64

In [151]:
# Convert the dictionary to a Pandas series
print("Converted series:")

ser.to_dict()


Converted series:


{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

**6. Write a Pandas program to convert a NumPy array to a Pandas series.**

In [153]:
# Original Data : [10, 20, 30, 40, 50]
# Create a numpy array with this data
print("NumPy array:")

arr=np.array([10,20,30,40,50])
arr

NumPy array:


array([10, 20, 30, 40, 50])

In [155]:
# Convert a NumPy array to this Pandas series.
print("Converted Pandas series:")

ds=pd.Series(arr)
ds


Converted Pandas series:


0    10
1    20
2    30
3    40
4    50
dtype: int64

**12. Write a Pandas program to add some data to an existing Series.**|

In [156]:
# Original Data : ['100', '200', 'python', '300.12', '400']
# Built a pandas Series with this data
print("Original Data Series:")
Original_Data = ['100', '200', 'python', '300.12', '400']
ser=pd.Series(Original_Data)
ser

Original Data Series:


0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [178]:
# Add ['500', 'php'] to the original Data Series
print("\nData Series after adding some data:")

ser.append(pd.Series(["500", "php"]))



Data Series after adding some data:


0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

**13. Write a Pandas program to create a subset of a given series based on value and condition.**

In [181]:
# Original Data : [0,1,2,3,4,5,6,7,8,9,10]
# Built a pandas Series with this data
print("Original Data Series:")
dser=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
dser

Original Data Series:


0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [185]:
# Create a new series with data with a value less than 6
print("\nSubset of the above Data Series:")

dser[dser<6]



Subset of the above Data Series:


0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64